// src/public/components/dropdown.vue
<template>
    <div :class="['drop' + type, {show: open}]">
        <slot name="button">
            <button :id="_uid + '-dropdown'" ref="toggle" class="btn btn-sm dropdown-toggle" :class="['btn-' + colour, buttonClass]"
                type="button" data-toggle="dropdown" aria-haspopup="true" :aria-expanded="open ? 'true' : 'false'"
                :disabled="disabled" @click.stop="open = !open"
            >
                <slot name="label">{{ label }}</slot>
            </button>
        </slot>

        <div ref="menu" class="dropdown-menu" :class="[{show: open, 'dropdown-menu-right': align === 'right'}, menuClass]"
            :aria-labelledby="_uid + '-dropdown'"
        >
            <slot />
        </div>
    </div>
</template>

<script>
    export default {
        props: {
            disabled: {type: Boolean},
            label: {type: String, default: 'Menu'},
            colour: {type: String, validator: value => ['default', 'dark'].includes(value), default: 'default'},
            type: {type: String, validator: value => ['down', 'up', 'left', 'right'].includes(value), default: 'down'},
            align: {type: String, validator: value => ['left', 'right'].includes(value), default: 'left'},
            buttonClass: {default: () => ({})},
            menuClass: {default: () => ({})},
        },
        data() {
            return {
                open: false,
            };
        },
        watch: {
            disabled(disabled) {
                if (disabled) this.open = false;
            },
            open(open) {
                if (open) this.$emit('opened'), document.body.addEventListener('click', this.close, true);
                else this.$emit('closed'), document.body.removeEventListener('click', this.close);
            },
        },
        destroy() {
            document.body.removeEventListener('click', this.close);
        },
        methods: {
            close(event) {
                if (event && event.target === this.$refs.toggle) return;

                this.open = false;
            },
        },
    };
</script>

// src/public/react/components/Dropdown.tsx
import * as React from 'react';
import {bind} from '../util/decorators';
import uid from '../util/component-id';

export interface DropdownProps {
    children: React.ReactNode;
    disabled?: boolean; // || false
    label?: string | React.ReactNode; // || 'Menu'
    colour?: 'default' | 'dark'; // || 'default'
    type?: 'down' | 'up' | 'left' | 'right'; // || 'down'
    align?: 'left' | 'right'; // || 'left'
    button?: React.ReactNode;
    buttonClass?: string;
    menuClass?: string;
    onOpen?: () => void;
    onClose?: () => void;
}

interface DropdownState {
    open: boolean;
}

export default class Dropdown extends React.PureComponent<DropdownProps, DropdownState> {
    private _uid = uid();

    state = {
        open: false,
    };

    render() {
        return <div className={[
            'drop' + (this.props.type ?? 'down'),
            this.state.open ? 'show' : null,
        ].filter(c => c).join(' ')}>
            {this.props.button ?? this.renderButton()}

            <div className={[
                'dropdown-menu',
                this.state.open ? 'show' : null,
                this.props.align === 'right' ? 'dropdown-menu-right' : null,
                this.props.menuClass,
            ].filter(c => c).join(' ')} aria-labelledby={this._uid + '-dropdown'}>
                {this.props.children}
            </div>
        </div>;
    }

    renderButton() {
        return <button
            id={this._uid + '-dropdown'}
            className={[
                'btn', 'btn-sm', 'dropdown-toggle',
                'btn-' + (this.props.colour ?? 'default'),
                this.props.buttonClass,
            ].filter(c => c).join(' ')}
            type="button"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded={this.state.open ? 'true' : 'false'}
            disabled={this.props.disabled ?? false}
            onClick={this.toggle}
        >
            {this.props.label ?? 'Menu'}
        </button>;
    }

    @bind
    toggle() {
        this.setState(prevState => ({
            open: !prevState.open,
        }));
    }

    open() {
        this.setState({
            open: true,
        });
    }

    @bind
    close() {
        this.setState({
            open: false,
        });
    }

    componentDidUpdate(prevProps: Readonly<DropdownProps>, prevState: Readonly<DropdownState>) {
        if (this.state.open && !prevState.open) {
            document.body.addEventListener('click', this.close, true);
            this.props.onOpen?.();
        }
        if (!this.state.open && prevState.open) {
            document.body.removeEventListener('click', this.close);
            this.props.onClose?.();
        }
    }

    static getDerivedStateFromProps(props: Readonly<DropdownProps>, state: Readonly<DropdownState>) {
        if (props.disabled && state.open) {
            return {
                open: false,
            };
        }

        return null;
    }

    componentWillUnmount() {
        document.body.removeEventListener('click', this.close);
    }
}
